version: '3'

services:
  evilginx2:
    container_name: evilginx2
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 53:53/udp
    command: ["/bin/bash"]
    #command: ["/bin/evilginx", "-p", "/app/phishlets", "-debug", "-developer"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app/:/root/.evilginx
      - ./app/phishlets:/app/phishlets
    stdin_open: true
    tty: true

  bobber:
    image: ubuntu:latest  # Ubuntu base image for Bobber
    container_name: bobber
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    command: /bin/bash -c "git clone https://github.com/Flangvik/Bobber.git && cd Bobber && ./bobber.py"
    depends_on:
      - evilginx2

  graphrunner:
    image: graphrunner  # .NET runtime for GraphRunner
    container_name: graphrunner
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    command: /bin/bash -c "git clone https://github.com/dafthack/GraphRunner.git && cd GraphRunner && dotnet run"
    #command: "Import-Module .\GraphRunner.ps1"
    depends_on:
      - evilginx2

networks:
  mynetwork:
    driver: bridge

volumes:
  shared-data:
    driver: local
