version: '3'

services:
  evilginx2:
    build:
      context: .
      dockerfile: Evilginx2-docker/Dockerfile
    container_name: 3BP_EvilGinx2
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 53:53/udp
    networks:
      - mynetwork
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./Evilginx2-docker/blacklist.txt:/root/.evilginx
      - ./config.json:/app/config.json
      - ./Evilginx2-docker/setup.sh:/app/setup.sh
      - ./Evilginx2-docker/phishlets:/app/phishlets
      - shared-data:/shared-data  # Shared volume
      - shared_EG2_DB:/root/.evilginx
    user: root
    command: ["/bin/sh", "-c", "mkdir -p /shared-data/EG2_DB /shared-data/fresh-data /shared-data/used-data && /bin/evilginx"] #Make this Entrypoint.sh setup.sh
    #command: ["/bin/bash"]
    #command: ["/bin/evilginx", "-p", "/app/phishlets", "-debug", "-developer"]
    stdin_open: true
    tty: true
    
  bobber:
    build:
      context: .
      dockerfile: Bobber-docker/Dockerfile
    image: ubuntu:latest  # Ubuntu base image for Bobber
    container_name: bobber
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    #command: ["/bin/sh", "-c", "mkdir -p /shared-data/fresh-data /shared-data/used-data"]
    depends_on:
      - evilginx2

  graphrunner:
    build:
      context: .
      dockerfile: GraphRunner-docker/Dockerfile
    image: graphrunner  # .NET runtime for GraphRunner
    container_name: graphrunner
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    #command: /bin/bash -c "git clone https://github.com/dafthack/GraphRunner.git && cd GraphRunner && dotnet run"
    #command: "Import-Module .\GraphRunner.ps1"
    depends_on:
      - evilginx2

networks:
  mynetwork:
    driver: bridge

volumes:
  shared-data:
    driver: local
  shared_EG2_DB:
    driver: local
    driver_opts:
      type: none
      device: /root/.evilginx
      o: bind
