version: '3'

services:
  evilginx2:
    build:
      context: .
      dockerfile: Evilginx2-docker/Dockerfile
    container_name: 3DP_Evilginx2
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 53:53/udp
    networks:
      - mynetwork
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./Evilginx2-docker/blacklist.txt:/root/.evilginx/blacklist.txt
      - ./config.json:/app/config.json
      - ./Evilginx2-docker/setup.sh:/app/setup.sh
      - ./Evilginx2-docker/phishlets:/app/phishlets
      - shared-data:/root/.evilginx # Shared volume
    user: root
    entrypoint: ["/app/setup.sh"]
    stdin_open: true
    tty: true
    
  bobber:
    build:
      context: .
      dockerfile: Bobber-docker/Dockerfile
    image: ubuntu:latest  # Ubuntu base image for Bobber
    container_name: 3DP_Bobber
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    #command: ["/bin/sh", "-c", "mkdir -p /shared-data/fresh-data /shared-data/used-data"]
    depends_on:
      - evilginx2

  graphrunner:
    build:
      context: .
      dockerfile: GraphRunner-docker/Dockerfile
    image: graphrunner  # .NET runtime for GraphRunner
    container_name: 3DP_Graphrunner
    volumes:
      - shared-data:/shared-data  # Shared volume
    networks:
      - mynetwork
    working_dir: /app
    #command: /bin/bash -c "git clone https://github.com/dafthack/GraphRunner.git && cd GraphRunner && dotnet run"
    #command: "Import-Module .\GraphRunner.ps1"
    depends_on:
      - evilginx2

networks:
  mynetwork:
    driver: bridge

volumes:
  shared-data:
    driver: local
